CREATE OR ALTER PROCEDURE usp_GenerateEligibleLetters
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @Today DATE = CAST(GETDATE() AS DATE);

    WITH EligibleRecoveries AS (
        SELECT A.ACPR_REF_ID, A.ACPR_NET_AMT, A.ACPR_CREATE_DT, A.ACPR_STS
        FROM ACPR A
        WHERE A.ACPR_STS = 'A'
            AND A.ACPR_NET_AMT >= 25
            AND DATEDIFF(DAY, A.ACPR_CREATE_DT, @Today) >= 30
            AND NOT EXISTS (
                SELECT 1 FROM ACRH H 
                WHERE H.ACPR_REF_ID = A.ACPR_REF_ID AND H.ACRH_EVENT_TYPE = 'W' AND H.ACRH_MCTR_RSN = 'HOLD'
            )
            AND NOT EXISTS (
                SELECT 1 FROM STATUS S 
                WHERE S.ACPR_REF_ID = A.ACPR_REF_ID AND S.STATUS = 'LETTER_SENT'
            )
    )
    INSERT INTO STATUS (ACPR_REF_ID, STATUS, STATUS_DATE, UPDATED_BY, COMMENTS)
    SELECT E.ACPR_REF_ID, 'LETTER_SENT', @Today, 'system_proc', 'Auto-generated by usp_GenerateEligibleLetters'
    FROM EligibleRecoveries E;

    PRINT 'Letter generation complete.';
END;