CREATE OR ALTER VIEW vw_RecoveryAgingDetail AS
SELECT 
    A.ACPR_REF_ID,
    A.ACPR_CREATE_DT,
    DATEDIFF(DAY, A.ACPR_CREATE_DT, GETDATE()) AS Days_Old,
    H.CURRENT_STATUS,
    H.CURRENT_NET_AMT,
    P.PROVIDER_NAME,
    P.CLCL_NTWK_IND AS Network_Type
FROM ACPR A
JOIN HEADER H ON A.ACPR_REF_ID = H.ACPR_REF_ID
LEFT JOIN PROVIDERS P ON A.ACPR_PAYEE_ID = P.PRPR_ID;