CREATE OR ALTER VIEW vw_CurrentRecoverySnapshot AS
SELECT 
    H.ACPR_REF_ID,
    H.CURRENT_STATUS,
    H.CURRENT_NET_AMT,
    H.STATUS_DT AS Last_Updated,
    A.ACPR_CREATE_DT,
    A.ACPR_TYPE,
    A.ACPR_SUB_TYPE,
    A.EXCD_ID,
    A.ACPR_PAYEE_ID,
    P.PROVIDER_NAME,
    P.CLCL_NTWK_IND AS Network_Type,
    P.IS_VA
FROM HEADER H
JOIN ACPR A ON A.ACPR_REF_ID = H.ACPR_REF_ID
LEFT JOIN PROVIDERS P ON A.ACPR_PAYEE_ID = P.PRPR_ID;