CREATE TABLE ACPR (
    ACPR_REF_ID       VARCHAR(20) PRIMARY KEY,
    ACPR_SUB_TYPE     VARCHAR(10) NOT NULL,
    ACPR_TYPE         VARCHAR(5) NOT NULL,
    ACPR_CREATE_DT    DATE NOT NULL,
    ACPR_NET_AMT      DECIMAL(10,2) NOT NULL,
    ACPR_STS          CHAR(1) NOT NULL,
    ACPR_PAYEE_ID     VARCHAR(15) NOT NULL,
    EXCD_ID           VARCHAR(5),
    INSURANCE_NUM     VARCHAR(20)
);

CREATE TABLE PROVIDERS (
    PRPR_ID         VARCHAR(15) PRIMARY KEY,
    PROVIDER_NAME   VARCHAR(100) NOT NULL,
    CLCL_NTWK_IND   CHAR(1) NOT NULL,
    IS_VA           BIT NOT NULL,
    WMDS_SEQ_NO     INT
);

CREATE TABLE HEADER (
    HEADER_ID        INT IDENTITY(1,1) PRIMARY KEY,
    ACPR_REF_ID      VARCHAR(20) NOT NULL,
    CURRENT_STATUS   VARCHAR(20) NOT NULL,
    CURRENT_NET_AMT  DECIMAL(10,2) NOT NULL,
    STATUS_DT        DATE NOT NULL,
    CONSTRAINT FK_HEADER_ACPR FOREIGN KEY (ACPR_REF_ID) REFERENCES ACPR(ACPR_REF_ID)
);

CREATE TABLE STATUS (
    STATUS_ID      INT IDENTITY(1,1) PRIMARY KEY,
    ACPR_REF_ID    VARCHAR(20) NOT NULL,
    STATUS         VARCHAR(20) NOT NULL,
    STATUS_DATE    DATE NOT NULL,
    UPDATED_BY     VARCHAR(30) NOT NULL,
    COMMENTS       VARCHAR(255),
    CONSTRAINT FK_STATUS_ACPR FOREIGN KEY (ACPR_REF_ID) REFERENCES ACPR(ACPR_REF_ID)
);

CREATE TABLE ACRH (
    ACRH_ID          INT IDENTITY(1,1) PRIMARY KEY,
    ACPR_REF_ID      VARCHAR(20) NOT NULL,
    ACPR_SUB_TYPE    VARCHAR(10) NOT NULL,
    ACRH_EVENT_TYPE  CHAR(1) NOT NULL,
    ACRH_MCTR_RSN    VARCHAR(20) NOT NULL,
    ACRH_AMT         DECIMAL(10,2),
    EVENT_DT         DATE NOT NULL,
    CONSTRAINT FK_ACRH_ACPR FOREIGN KEY (ACPR_REF_ID) REFERENCES ACPR(ACPR_REF_ID)
);