CREATE OR ALTER VIEW vw_WriteOffSummary AS
SELECT 
    H.ACPR_REF_ID,
    H.ACRH_AMT AS WriteOffAmount,
    H.EVENT_DT AS WriteOffDate,
    P.PROVIDER_NAME,
    P.CLCL_NTWK_IND AS Network_Type,
    P.IS_VA
FROM ACRH H
JOIN ACPR A ON H.ACPR_REF_ID = A.ACPR_REF_ID
LEFT JOIN PROVIDERS P ON A.ACPR_PAYEE_ID = P.PRPR_ID
WHERE H.ACRH_MCTR_RSN = 'SWOF';