CREATE OR ALTER VIEW vw_RecoveryStatusHistory AS
SELECT 
    S.STATUS_ID,
    S.ACPR_REF_ID,
    S.STATUS,
    S.STATUS_DATE,
    S.UPDATED_BY,
    S.COMMENTS,
    A.ACPR_CREATE_DT,
    P.PROVIDER_NAME,
    P.CLCL_NTWK_IND AS Network_Type
FROM STATUS S
JOIN ACPR A ON S.ACPR_REF_ID = A.ACPR_REF_ID
LEFT JOIN PROVIDERS P ON A.ACPR_PAYEE_ID = P.PRPR_ID;